name: Lint

on:
  push:
    branches:
      - main
    paths:
      - lucy/**
      - .github/workflows/pylint.yml
  pull_request:
    branches:
      - main
    paths:
      - lucy/**
      - .github/workflows/pylint.yml

defaults:
  run:
    working-directory: ./lucy

jobs:
  py-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install .[lint,test]
      - name: Run pylint
        run: |
          pylint --recursive=y .
      - name: Run yapf
        run: |
          yapf -d -r .
      - name: Run mypy
        run: |
          mypy .
